@startuml
hide circle
skinparam classAttributeIconSize 0

entity "Работник" as employee <<справочник>> {
    --
    +Фамилия
    +Имя
    +Отчество
    +Пол
    +Дата рождения
    +Фотография
    +Дата найма
    +Дата увольнения
    +Причина увольнения
    +Токен аутентификации
    +Логин
    +Свертка пароля
}

entity "Должность" as position <<справочник>> {
    --
    +Наименование
}

entity "Структурное\nподразделение" as organizational_unit <<справочник>> {
    --
    +Наименование
    +Время начала работы
    +Время окончания работы
}

entity "Организация" as organization <<справочник>> {
    --
    +Наименование
    +Директор
    +Главный бухгалтер
    +Время начала работы
    +Время окончания работы    
}

entity "Деятельность" as activity <<справочник>> {
    --
    +Наименование
    +Описание
}

entity "Зарегистрированное\nсобытие" as actual_event {
    --
    +Дата/время начала
    +Дата/время окончания
    +Описание
}

entity "Запланированная\nработа" as scheduled_work {
    --
    +Дата начала
    +Дата окончания
    +День недели
    +Тип дня
    +Время начала
    +Время окончания
}

entity "Событие" as event <<справочник>> {
    --
    +Название
}

entity "Сеанс" as session {
    --
    +Работник
    +Приложение
    +EAM-клиент
}

entity "Приложение" as application <<справочник>> {
    --
    +Наименование
    +Описание
    +Категория
}

entity "ЕАМ-агент" as eam <<справочник>> {
    --
    +IP-адрес хоста
    +Наименование хоста
}

entity "Политика\nучета\nвремени" as policy <<справочник>> {
    --
    +Наименование
    +Режим обеденного перерыва
    +Допустимое опоздание
    +Допустимый ранний уход
    +Допустимое отклонение от\nзапланированной работы
}

entity "Роль" as role <<справочник>> {
    --
    +Наименование
    +Описание
}

entity "Права доступа" as access <<справочник>> {
    --
    +Наименование
    +Описание
}

entity "Назначенные права" as access_assignment {
    --
    +Роль
    +Права доступа
}

entity "Назначенная роль" as role_assignment {
    --
    +Работник
    +Роль
}

organization ||--|{ organizational_unit : Включает >
position ||--|{ employee : Замещает <
position }|--|| organizational_unit : Включает <
'employee ||--|{ actual_event : Осуществляет >
employee ||--|{ scheduled_work : Выполняет >
employee ||--|{ session : Инициирует >
actual_event }|--|| event : Тип события <
scheduled_work }|--|| activity : Тип деятельности <
session ||--|{ actual_event : Включает >
application |o--|{ session : Запуcкается >
eam ||--|{ session : Отслеживает >
policy ||--|{ employee : Применяется >
role_assignment }|--|| employee : Присвоена >
role_assignment }|--||role : Назначена <
access_assignment }|--|| role : Присвоены >
access_assignment }|--|| access : Назначены <

@enduml